---
version: '3.2'

services:
  iqengine:
    build:
      context: .
    image: iqengine:latest
    volumes:
      - /tmp/recordings
    # We have to forward the env file env vars to the container
    environment:
      IN_MEMORY_DB: ${IN_MEMORY_DB}
      IQENGINE_CONNECTION_INFO: ${IQENGINE_CONNECTION_INFO}
      IQENGINE_FEATURE_FLAGS: ${IQENGINE_FEATURE_FLAGS}
      IQENGINE_PLUGINS: ${IQENGINE_PLUGINS}
      IQENGINE_METADATA_DB_CONNECTION_STRING: ${IQENGINE_METADATA_DB_CONNECTION_STRING}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MINIO_REGION: ${MINIO_REGION:-us-east-1}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_PREFIX: ${MINIO_PREFIX:-}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_DATASOURCE_NAME: ${MINIO_DATASOURCE_NAME:-FAST MinIO SigMF}
      MINIO_VERIFY_SSL: ${MINIO_VERIFY_SSL:-true}
    depends_on:
      - mongo
    ports:
      - 3000:3000
  plugins:
    build:
      context: plugins
    image: plugins:latest
    depends_on:
      - mongo
    ports:
      - 8000:8000
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
